### PR TITLE
ActiveMQ client integrated into Talos Operator

### PR DESCRIPTION
**Pull request by bl2060**
The client is part of the build process, uses the existing logging module, and can receive and log messages it receives from the ActiveMQ broker (version 6.1.3).

Features not implemented in this PR (but will be later):

- Sending back data (e.g. logs, command returns)
- Command handling

### CODE REVIEW

**Comment by nlc4447** [comment]
timestamp.h:
    - line 50-58 looks like a documentation template?
    - also just bloat comment definitions (will we be using these?)
    - line 121 parameter is indicated by wrong name
    - ^^ line 134 as well
    - line 138 function missing documentation?
    -- do we really need this many functions to get a local timestamp? What, if anything, will we be using UTC for?
    -- also what is the 'if' statement at the end of the file for?
timestamp.c:
    - is it considered bad practice to have in-file comments in C? Might be helpful for anyone external trying to 					understand the code.
    -- I realized this file is probably only utilized by the logging module? is this correct?
tamq.cpp
    - quick doc comment for each function would be helpful
    - in onMessage() function, why is count declared locally? Based on the code it looks like the value will always be 1 because it is incremented once, but there is no iteration in the function
    - what is 'auto-ack mode?' doesn't sound like we should be acknowledging without a director connected (but I def 				could be wrong on what this means)
-- overall looks pretty good but I think it would be helpful to have document headers for each document at least including 		the file's purpose to the app as well as author / version info, etc.  For instance, I don't really have a clue as to what the files with 's_list' are for unless I read through all of it and determing (am still fuzzy) that it is a list of movements to execute on the arm.
-- also just including doc comments will be helpful for anyone wanting to utilize this.

**Comment by bl2060** [comment]
timestamp.h: 
>line 50-58 looks like a documentation template?

Yes
> also just bloat comment definitions (will we be using these?)

Clarification needed

> line 121 parameter is indicated by wrong name 
 line 134 as well: I think you might be looking at them wrong?
line 138 function missing documentation?

C doc strings are listed above the relevant function, as opposed to python which is usually the first thing in the body of the function.

> do we really need this many functions to get a local timestamp? What, if anything, will we be using UTC for?

UTC is currently the default for this library (personal preference). This module started out as a generic library for my personal projects, so I wanted to have a lot of options for various applications.

> also what is the 'if' statement at the end of the file for?

Timestamp is written in C. For it to work with CPP, it needs the "extern C" at the top. The if statement allows the compiler to automatically determine if it is being compiled into C or CPP.


timestamp.c: 
> is it considered bad practice to have in-file comments in C? Might be helpful for anyone external trying to understand the code

in-file comments are very much good practice, I just didn't write any. Compared to the rest of the logging module, the timestamp.c code seemed mostly self documenting.
>I realized this file is probably only utilized by the logging module? is this correct?

So far, yes.

tamq.cpp:
>quick doc comment for each function would be helpful

>in onMessage() function, why is count declared locally? Based on the code it looks like the value will always be 1 because it is incremented once, but there is no iteration in the function 

>what is 'auto-ack mode?' doesn't sound like we should be acknowledging without a director connected (but I def could be wrong on what this means)

These I more-or-less directly lifted from the AMQ example code. It hasn't quite been tailored to our implementation fully yet. My goal with this PR was to simply merge the functioning AMQ client into our executable/build process, tailoring it in another PR. I'm currently working on that process with a MessageHandler for processing commands, if you think it's a better idea to simply wait for that to be done (I've started leaning that way myself).

>overall looks pretty good but I think it would be helpful to have document headers for each document at least including the file's purpose to the app as well as author / version info, etc. For instance, I don't really have a clue as to what the files with 's_list' are for unless I read through all of it and determing (am still fuzzy) that it is a list of movements to execute on the arm. 

>also just including doc comments will be helpful for anyone wanting to utilize this.

Good points, I'll add them. (S_List is just a singly linked list)

**Review by nlc4447 — APPROVED** [review]
Wow you wrote a ton of code!

Looks good to me.

**Comment by bl2060** [comment]
Confidence: 2/5
ActiveMQ works, sort of.
Numerous bugs are known, with no known fix. As its an external dependency, theres not a ton we can do. It's open source, so its possible to fix, but not practical. Plans are underway to replace it with a method that isn't such a pain to compile and build.

**Pull request merged**
